# fly.toml app configuration file generated for pollinatr on 2023-05-26T12:16:34-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pollinatr"
primary_region = "ord"
kill_signal = "SIGTERM"
kill_timeout = "20s"

[experimental]
  auto_rollback = true

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "pollinatr.fly.dev"
  PORT = "4000"

[[services]]
  protocol = "tcp"
  internal_port = 4000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 600
    soft_limit = 500

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "10s"
    grace_period = "10s"
    restart_limit = 0
